import Header from "./Header"
import styles from "../styles/Layout.module.css"
import Footer from "./Footer"
import SideNav from "./SideNav"

const Layout = ({ children, props }) => {
  return (
    <>
      {/*<Head>
        {" "}
        <title>Musical Gaucamole</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>*/}
      <div className={styles.grid}>
        <SideNav />
        <Header />
        <main className={styles.content__container}>{children}</main>
        <Footer />
      </div>
    </>
  )
}

export default Layout
