import Head from "next/head"
import { useRouter } from "next/router"
import styles from "../styles/Login.module.css"
import { useAuth } from "../context/auth"

export default function Login() {
  const router = useRouter()
  const { authorizationCode } = useAuth()

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles["o-container"]}>
          <div className={styles.container}>
            <h1 className={styles.heading}> musical guacamole</h1>
            <p className={styles.subheading}>
              musical gaucamole lets you make forks of your favorite public
              spotify playlists so you can make additions and keep it synced
              with the original.{" "}
            </p>
            <button
              className={styles.btn}
              onClick={async () => await authorizationCode(router)}
            >
              {" "}
              log in with spotify{" "}
            </button>
          </div>
        </main>
      </div>
    </>
  )
}
