import Head from "next/head"
import { useRouter } from "next/router"
//import { supabase } from "../lib/supabase"
//import Voronoi from '../components/Voronoi'
import styles from "../styles/Home.module.css"
import { authorizationCode, getAuthTokens } from "../lib/auth/authorize"
import { useAuth } from "../context/auth"
import { useEffect } from "react"

export default function Home() {
  console.log("tear")
  const router = useRouter()
  const { session, loading } = useAuth()

  //useEffect(() => {
  //  if (session) {
  //    router.push("/home")
  //    return
  //  }
  //}, [session])

  const handleAuth = async () => {
    const url = await authorizationCode(router)

    //await supabase.auth.signIn({
    //  provider: "spotify",
    //  options:{
    //    scopes:
    //      "user-read-private user-read-email playlist-read-private playlist-read-collaborative user-read-currently-playing user-top-read playlist-modify-public playlist-modify-private",
    //  },
    //})
  }

  if (loading) {
    return <> </>
  } else {
    return !session ? (
      <>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <button onClick={handleAuth}> Log In </button>
          </main>
        </div>
      </>
    ) : (
      <></>
    )
  }
}
